/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ClienteDAO;
import Entity.Cliente;
import javax.swing.JOptionPane;
//import Utils.ComboBoxData;
//import Utils.Util;
//import Utils.VerificadorDeEntradas;
//import java.util.Calendar;
//import java.util.GregorianCalendar;

/**
 *
 * @author Wagner Chaves
 */
public class NovoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NovoCliente
     */
    public NovoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvar = new javax.swing.JButton();
        jLabelCadNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabelRG = new javax.swing.JLabel();
        tfRg = new javax.swing.JFormattedTextField();
        jLabelCPF = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        jLabelDataDeNasc = new javax.swing.JLabel();
        tfDataNasc = new javax.swing.JFormattedTextField();
        jLabel1CadastroDeCliente = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        tfCep = new javax.swing.JFormattedTextField();
        jLabelBairro = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        jLabelLogradouro1 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabelUF = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        jLabelCep1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfObs = new javax.swing.JTextArea();
        jLabelNomeInvld = new javax.swing.JLabel();
        jLabelNomeInvld2 = new javax.swing.JLabel();
        jLabelNomeInvld3 = new javax.swing.JLabel();
        jLabelNomeInvld4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelCadNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadNome.setText("Nome:");

        tfNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelRG.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelRG.setText("RG:");

        try {
            tfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfRg.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelCPF.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCPF.setText("CPF:");

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCpfFocusLost(evt);
            }
        });

        jLabelDataDeNasc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDataDeNasc.setText("Data de Nasc:");

        try {
            tfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDataNasc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataNascActionPerformed(evt);
            }
        });

        jLabel1CadastroDeCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1CadastroDeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1CadastroDeCliente.setText("CADASTRO DE CLIENTE");
        jLabel1CadastroDeCliente.setToolTipText("");
        jLabel1CadastroDeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1CadastroDeCliente.setMaximumSize(new java.awt.Dimension(740, 80));
        jLabel1CadastroDeCliente.setMinimumSize(new java.awt.Dimension(740, 80));
        jLabel1CadastroDeCliente.setPreferredSize(new java.awt.Dimension(740, 70));
        jLabel1CadastroDeCliente.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabelLogradouro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLogradouro.setText("Endereço:");

        tfEndereco.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelCep.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCep.setText("CEP:");

        try {
            tfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCep.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabelBairro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelBairro.setText("Bairro:");

        tfBairro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelCelular.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCelular.setText("Telefone:");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelLogradouro1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLogradouro1.setText("Cidade:");

        tfCidade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabelUF.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelUF.setText("UF:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.setMinimumSize(new java.awt.Dimension(56, 33));
        cbEstado.setPreferredSize(new java.awt.Dimension(56, 33));

        jLabelCep1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCep1.setText("Observações:");

        tfObs.setColumns(20);
        tfObs.setRows(5);
        jScrollPane1.setViewportView(tfObs);

        jLabelNomeInvld.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld.setText("*");

        jLabelNomeInvld2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld2.setText("*");

        jLabelNomeInvld3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld3.setText("*");

        jLabelNomeInvld4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld4.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelDataDeNasc)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNomeInvld3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(276, 276, 276))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelLogradouro)
                                                .addGap(278, 278, 278))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelLogradouro1)
                                                .addGap(25, 25, 25)
                                                .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addComponent(jLabelUF)
                                        .addGap(19, 19, 19)
                                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabelRG)
                                        .addGap(231, 231, 231)
                                        .addComponent(jLabelCPF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelBairro)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCadNome)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(29, 29, 29)
                                                        .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(120, 120, 120)
                                                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCep1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCep)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabelCelular)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelNomeInvld4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1CadastroDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeInvld, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeInvld2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1CadastroDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeInvld))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRG)
                            .addComponent(jLabelCPF)
                            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeInvld2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataDeNasc)
                    .addComponent(jLabelBairro)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeInvld3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogradouro1)
                    .addComponent(jLabelUF)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCep)
                    .addComponent(jLabelCelular)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeInvld4))
                .addGap(18, 18, 18)
                .addComponent(jLabelCep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente inserir este funcionário", "Salvar", JOptionPane.YES_NO_OPTION) == 0){
            Cliente cli = new Cliente(tfNome.getText(), tfDataNasc.getText(), tfCpf.getText(), tfRg.getText(), tfTelefone.getText(), tfEndereco.getText(), tfBairro.getText(), tfCidade.getText(), tfCep.getText(), cbEstado.getSelectedItem() + "", tfObs.getText());
            ClienteDAO cliDAO = new ClienteDAO();
            cliDAO.inserir(cli);
            dispose();                
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void tfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusLost

    }//GEN-LAST:event_tfCpfFocusLost

    private void tfDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataNascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1CadastroDeCliente;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadNome;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCep1;
    private javax.swing.JLabel jLabelDataDeNasc;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelLogradouro1;
    private javax.swing.JLabel jLabelNomeInvld;
    private javax.swing.JLabel jLabelNomeInvld2;
    private javax.swing.JLabel jLabelNomeInvld3;
    private javax.swing.JLabel jLabelNomeInvld4;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataNasc;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextArea tfObs;
    private javax.swing.JFormattedTextField tfRg;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
